# Generated by Django 3.0.6 on 2020-06-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastsandroasts',
            name='votescore',
        ),
    ]
